import { auth, db, ROOT_PATH } from "../js/firebase-config.js";
import { requireAuth, logoutUser } from "../js/auth.js";
import { collection, addDoc, getDocs, query, where, orderBy, serverTimestamp, doc, getDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const $=id=>document.getElementById(id); let me=null, properties=[], current=null;
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
function toast(x){const e=$("toast");e.textContent=x;e.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.add("hidden"),2600)}
function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openModal(title,html){$("modalTitle").textContent=title;$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
async function loadProperties(){const q=query(collection(db,"properties"),where("ownerUid","==",me.uid)); const s=await getDocs(q); properties=s.docs.map(d=>({id:d.id,...d.data()})); await renderProperties();}
async function renderProperties(){let rooms=0,occ=0,rent=0;for(const p of properties){const s=await getDocs(collection(db,"properties",p.id,"rooms"));p._rooms=s.docs.map(d=>({id:d.id,...d.data()}));rooms+=p._rooms.length;occ+=p._rooms.filter(r=>r.status==="occupied").length;rent+=p._rooms.reduce((a,r)=>a+Number(r.monthlyRent||0),0)}$("statProperties").textContent=properties.length;$("statRooms").textContent=rooms;$("statOccupied").textContent=occ;$("statRent").textContent=money(rent);$("propertyList").innerHTML=properties.length?properties.map(p=>`<div class="card" data-id="${p.id}" style="cursor:pointer"><div class="row"><div><h3>${esc(p.name)}</h3><div class="person-meta">${esc(p.address||"")}${p.city?", "+esc(p.city):""}</div></div><span class="pill pill-blue">${p._rooms.length} rooms</span></div></div>`).join(""):`<div class="empty-state"><div class="emoji">🏠</div><h3>Add your first property</h3><p>Create a building/property and start managing rooms, tenants and rent.</p></div>`;document.querySelectorAll("#propertyList .card[data-id]").forEach(e=>e.onclick=()=>openProperty(e.dataset.id))}
function propertyForm(){openModal("Add Property",`<div class="field"><label>Property / Building Name</label><input id="fName" placeholder="Sharma Building" required></div><div class="field"><label>Address</label><input id="fAddress" placeholder="Full address"></div><div class="field"><label>City</label><input id="fCity" placeholder="Noida"></div><div class="field"><label>Description</label><textarea id="fDesc" rows="3" placeholder="Optional details"></textarea></div><button id="saveProperty" class="btn btn-primary">Create Property</button>`);$("saveProperty").onclick=async()=>{try{const name=$("fName").value.trim();if(!name)return toast("Property name is required");await addDoc(collection(db,"properties"),{ownerUid:me.uid,name,address:$("fAddress").value.trim(),city:$("fCity").value.trim(),description:$("fDesc").value.trim(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeModal();await loadProperties();toast("Property created") }catch(e){console.error(e);toast("Could not create property. Deploy latest firestore.rules.")}}}
async function openProperty(id){current=properties.find(p=>p.id===id);if(!current)return;$("dashboardView").classList.add("hidden");$("propertyView").classList.remove("hidden");$("propertyTitle").textContent=current.name;$("propertyMeta").textContent=[current.address,current.city].filter(Boolean).join(", ");await renderRooms()}
async function renderRooms(){const s=await getDocs(query(collection(db,"properties",current.id,"rooms"),orderBy("createdAt","desc")));current._rooms=s.docs.map(d=>({id:d.id,...d.data()}));$("roomList").innerHTML=current._rooms.length?current._rooms.map(r=>`<div class="card"><div class="row"><div><h3>Room ${esc(r.roomNumber||r.name||"")}</h3><div class="person-meta">${esc(r.type||"Room")} · ${r.status==="occupied"?"Occupied":"Vacant"}</div></div><div style="text-align:right"><b>${money(r.monthlyRent)}</b><div class="person-meta">Due ${esc(r.dueDate||"-")}</div></div></div><div class="person-meta" style="margin-top:10px">Tenant: ${esc(r.tenantName||"Not assigned")} ${r.tenantPhone?"· "+esc(r.tenantPhone):""}</div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn btn-outline editRoom" data-id="${r.id}" style="width:auto">Edit</button><button class="btn btn-primary rentRoom" data-id="${r.id}" style="width:auto">Rent Paid</button></div></div>`).join(""):`<div class="empty-state"><div class="emoji">🚪</div><h3>No rooms yet</h3><p>Add rooms with rent, tenant and status details.</p></div>`;document.querySelectorAll(".editRoom").forEach(b=>b.onclick=()=>roomForm(current._rooms.find(r=>r.id===b.dataset.id)));document.querySelectorAll(".rentRoom").forEach(b=>b.onclick=()=>paymentForm(current._rooms.find(r=>r.id===b.dataset.id)))}
function roomForm(room={}){openModal(room.id?"Edit Room":"Add Room",`<div class="field"><label>Room / Flat Number</label><input id="rNo" value="${esc(room.roomNumber||"")}" placeholder="3/3"></div><div class="field"><label>Room Type</label><select id="rType"><option>Single</option><option>Double</option><option>Flat</option><option>Other</option></select></div><div class="field"><label>Monthly Rent (₹)</label><input id="rRent" type="number" min="0" value="${Number(room.monthlyRent||0)}"></div><div class="field"><label>Due Date (day of month)</label><input id="rDue" type="number" min="1" max="31" value="${Number(room.dueDate||5)}"></div><div class="field"><label>Status</label><select id="rStatus"><option value="vacant">Vacant</option><option value="occupied">Occupied</option><option value="maintenance">Maintenance</option></select></div><div class="field"><label>Tenant Name</label><input id="rTenant" value="${esc(room.tenantName||"")}"></div><div class="field"><label>Tenant Mobile</label><input id="rPhone" value="${esc(room.tenantPhone||"")}" inputmode="tel"></div><button id="saveRoom" class="btn btn-primary">${room.id?"Save Changes":"Create Room"}</button>`);$("rType").value=room.type||"Single";$("rStatus").value=room.status||"vacant";$("saveRoom").onclick=async()=>{try{const data={roomNumber:$("rNo").value.trim(),type:$("rType").value,monthlyRent:Number($("rRent").value||0),dueDate:Number($("rDue").value||5),status:$("rStatus").value,tenantName:$("rTenant").value.trim(),tenantPhone:$("rPhone").value.trim(),updatedAt:serverTimestamp()};if(!data.roomNumber)return toast("Room number is required");if(room.id)await updateDoc(doc(db,"properties",current.id,"rooms",room.id),data);else await addDoc(collection(db,"properties",current.id,"rooms"),{...data,createdAt:serverTimestamp()});closeModal();await renderRooms();await loadProperties();toast(room.id?"Room updated":"Room created")}catch(e){console.error(e);toast("Permission denied. Deploy the latest firestore.rules.")}}}
function paymentForm(room){openModal("Record Rent Payment",`<div class="card" style="box-shadow:none;padding:0"><b>Room ${esc(room.roomNumber)}</b><div class="person-meta">${esc(room.tenantName||"No tenant")} · Due ${money(room.monthlyRent)}</div></div><div class="field"><label>Amount (₹)</label><input id="pAmt" type="number" value="${Number(room.monthlyRent||0)}"></div><div class="field"><label>Payment Mode</label><select id="pMode"><option>UPI</option><option>Cash</option><option>Bank Transfer</option></select></div><div class="field"><label>Month</label><input id="pMonth" type="month" value="${new Date().toISOString().slice(0,7)}"></div><button id="savePayment" class="btn btn-primary">Save Payment</button>`);$("savePayment").onclick=async()=>{try{await addDoc(collection(db,"properties",current.id,"rentPayments"),{roomId:room.id,roomNumber:room.roomNumber,tenantName:room.tenantName||"",amount:Number($("pAmt").value||0),mode:$("pMode").value,month:$("pMonth").value,paidBy:me.uid,createdAt:serverTimestamp()});closeModal();toast("Rent payment recorded")}catch(e){console.error(e);toast("Could not record payment")}}}
$("addPropertyBtn").onclick=propertyForm;$("addRoomBtn").onclick=()=>roomForm();$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("backBtn").onclick=()=>{$("propertyView").classList.add("hidden");$("dashboardView").classList.remove("hidden");loadProperties()};$("logoutBtn").onclick=async()=>{await logoutUser();location.href=ROOT_PATH+"index.html"};$("homeNav").onclick=()=>{$("propertyView").classList.add("hidden");$("dashboardView").classList.remove("hidden");loadProperties()};
requireAuth({expectedRole:"landlord",onReady:async(user,profile)=>{me=user;$("welcome").textContent=profile.name||user.displayName||"Makan Malik";$("loader").classList.add("hidden");$("app").classList.remove("hidden");try{await loadProperties()}catch(e){console.error(e);toast("Could not load properties. Check Firestore rules/indexes.")}}});
